name: Deploy Website To Production

on:
  push:
    branches:
    - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket for production
      run: |
        git config user.email "$GITHUB_ACTOR"
        git config user.name "$GITHUB_ACTOR"
        git remote set-url origin https://${{ secrets.GH_ACTION_TOKEN }}@github.com/nemac/sandbox.git
        npm install
        npm run build
        aws s3 sync ./dist/ s3://sandbox.nemac.org --acl public-read
        aws cloudfront create-invalidation --distribution-id E3H0SBJ02HEEPE --paths '/*'  
